### ISSUE TITLE
move Far Lands to a custom generator type

### ISSUE THREAD

**Issue by geniiii** [polgaria/FarLands#1]

**Comment by muzikbike** [comment]
not sure if i agree with this, I prefer the ability to play with far lands on large biomes/amplified/buffet, plus it sounds like it would be hell to get these options to work properly with the nether/end

**Comment by geniiii** [comment]
> not sure if i agree with this, I prefer the ability to play with far lands on large biomes/amplified/buffet, plus it sounds like it would be hell to get these options to work properly with the nether/end

That's why I've never completed this, I have no idea how it'd work with other dimensions..

**Comment by muzikbike** [comment]
i also prefer the ability to turn the far lands in and off at will, instead of having them locked on per world. can this ticket just be closed and attention returned to higher priority stuff?
