### ISSUE TITLE
Enchantment tables still use incorrect floats for player detection

### ISSUE THREAD

**Issue by muzikbike** [polgaria/FarLands#10]
![2019-08-18_23 10 23](https://user-images.githubusercontent.com/52297970/63231037-7aac8200-c20d-11e9-9fb5-0dd4aedab2da.png)
![2019-08-18_23 10 36](https://user-images.githubusercontent.com/52297970/63231038-7aac8200-c20d-11e9-9ce4-ba052536bc32.png)

**Comment by geniiii** [comment]
v1.6 (f0dc2d75a8bcb3a11d3e9c197a30e9afa1da207e) should fix this

**Comment by geniiii** [comment]
closing as v1.6 is now released

**Comment by muzikbike** [comment]
This is being fixed in vanilla in the next prerelease
