### ISSUE TITLE
Falling sand renders incorrectly

### ISSUE THREAD

**Issue by muzikbike** [polgaria/FarLands#11]
![2019-08-18_23 11 47](https://user-images.githubusercontent.com/52297970/63231045-99ab1400-c20d-11e9-876f-1f57d04389b4.png)

**Comment by muzikbike** [comment]
This is fixed in vanilla 19w39a, so unless you want the fix to be backported I'll go ahead and close this ticket.

**Comment by geniiii** [comment]
i don't plan on backporting anything from 1.6.x to 1.5.x
