### ISSUE TITLE
Allow terrain to generate and work out to x/z = +-9,223,372,037,854,775,807

### ISSUE THREAD

**Issue by muzikbike** [polgaria/FarLands#13]
Now this is obviously a pretty ridiculous suggestion, and is probably not possible without a lot of things completely breaking. But who knows, it just might be possible. Bartek over at cubic chunks had a smidge of success with it, although it was only done as a one-off experiment and not as an actual mod meant to work, and there were many errors with chunk rendering and plenty of other stuff.

**Comment by Niko-sk2x** [comment]
This is probably not really a feasible idea without a significant amount of effort. That little bit of success that I had with it was an experiment I did in 1.12.2 forgedev environment and I had to create hundreds of lines of patches just to get this

<details>
<summary>Click to show screenshot</summary>

![screenshot](https://i.imgur.com/xaPGP0z.png)

</details>

**Comment by muzikbike** [comment]
closing as the notice on this mod's read me has announced discontinuation for a while now - feel free to reopen in future if work starts again
