### ISSUE TITLE
Text goes off the screen

### ISSUE THREAD

**Issue by muzikbike** [polgaria/FarLands#15]
![2019-09-08_18 46 44](https://user-images.githubusercontent.com/52297970/64492160-13f91200-d269-11e9-8ce8-864a0330869a.png)

**Comment by geniiii** [comment]
oh. yea, i should probably make that shorter lol

**Comment by geniiii** [comment]
d5fed2835d58d154c609fd75e269828ab677e5db should close this, lower resolutions will have to suffer if not :sweat_smile:
