### ISSUE TITLE
Holding backspace in the coordinate scale modification boxes does not delete multiple characters

### ISSUE THREAD

**Issue by muzikbike** [polgaria/FarLands#18]
These ones:

![2019-09-09_00 51 26](https://user-images.githubusercontent.com/52297970/64496364-0f9a1c80-d29c-11e9-8d70-cb562ec0656a.png)

**Comment by geniiii** [comment]
i'm not quite sure if this is exclusive to the coordinate scales, iirc it was a vanilla issue

**Comment by muzikbike** [comment]
regarding the maybe: i'm definitely able to delete multiple characters when holding backspace on the seed input box, so vanilla seems to be working as expected

**Comment by muzikbike** [comment]
closing as the notice on this mod's readme has announced discontinuation for a while now - feel free to reopen in future if work starts again
