### ISSUE TITLE
Coordinate scale modification does not seem to move selector noise

### ISSUE THREAD

**Issue by muzikbike** [polgaria/FarLands#19]
I've been doing a bit of messing around lately, and I've noticed that the farther lands always seem to initiate at the default 1004065920 regardless of whatever value is set in the far lands settings.

![2019-09-09_01 16 39](https://user-images.githubusercontent.com/52297970/64496782-951fcb80-d2a0-11e9-8af7-a156fd6de45e.png)
![2019-09-09_01 16 45](https://user-images.githubusercontent.com/52297970/64496783-95b86200-d2a0-11e9-8d5b-a2a09e117f66.png)
![2019-09-09_01 20 12](https://user-images.githubusercontent.com/52297970/64496787-994be900-d2a0-11e9-9082-0a3c9e6f15d4.png)
![2019-09-09_01 20 20](https://user-images.githubusercontent.com/52297970/64496788-99e47f80-d2a0-11e9-9634-57a03f7ccbfa.png)

This made me think that the noise generator that causes the farther lands to happen, known to CubicWorldGen as selector noise, is not being moved along with the other noise generators.

To confirm my suspicions I decided to move the normal Far Lands super far away and teleporting to the usual farther lands point, and this resulted in terrain that very closely resembled my late 2018 cubicworldgen experiments with making selector noise overflow before normal far lands.

![2019-09-09_01 22 01](https://user-images.githubusercontent.com/52297970/64496826-e6c85600-d2a0-11e9-8a23-85927b17c464.png)
![2019-09-09_01 22 22](https://user-images.githubusercontent.com/52297970/64496829-e9c34680-d2a0-11e9-9200-a46f9ae673ed.png)

This bug does bring up an exciting prospect - it could be possible for selector noise to be made configurable completely independently of the other noise values responsible for conventional far lands, just like what is the case in the cubic chunks mod. I think this would be great.

**Comment by geniiii** [comment]
seeing this has made me realize that i accidentally left the estimates uneditable (which is why they're gray) after testing some code! whoops.. the joys of programming at 3am with 3 hours of sleep..

**Comment by muzikbike** [comment]
Should this be resolved in favour of #39?

**Comment by geniiii** [comment]
> Should this be resolved in favour of #39?

sure

**Comment by muzikbike** [comment]
was wondering, since making this noise generator independently adjustable seems as though it would be easier than resolving that bigger ticket overall
