### ISSUE TITLE
Option to remove the upper limit for terrain generation in the Nether and End

### ISSUE THREAD

**Issue by muzikbike** [polgaria/FarLands#20]
Currently it's still capped at y<128.
![2019-09-12_01 10 03](https://user-images.githubusercontent.com/52297970/64744094-571de400-d4fa-11e9-84b7-6755be7c5246.png)
![2019-09-12_01 10 43](https://user-images.githubusercontent.com/52297970/64744095-571de400-d4fa-11e9-8776-6dbffd31521b.png)

An option to toggle off this limit, if possible, would be much appreciated, so I could see just how mad this stuff can get. As for the Nether, keep the bedrock ceiling as is but allow netherrack to generate above it as normal if possible.

**Comment by geniiii** [comment]
![image](https://user-images.githubusercontent.com/24881499/68074096-20e53e00-fda0-11e9-985a-e5d801caac5f.png)
getting there

**Comment by geniiii** [comment]
should be done in 5025d6d742ab0e9a171a2dee9aa2522c8762cc92, but i wouldn't be surprised if any bugs show up
