### ISSUE TITLE
Particles from brewing stand lose precision

### ISSUE THREAD

**Issue by muzikbike** [polgaria/FarLands#22]
Since these are emitted by a block, like spawner particles and stuff, I'm led to suspect they won't require a rewrite of the particle packet.
![2019-09-28_03 27 02](https://user-images.githubusercontent.com/52297970/65810245-049e2200-e1a0-11e9-8334-feaee0b2c853.png)

**Comment by geniiii** [comment]
fixed in fb5c0735fa34d5b624964f33f980966bccab0b77
