### ISSUE TITLE
Rain/snow renders stretched out at high Y coordinates

### ISSUE THREAD

**Issue by muzikbike** [polgaria/FarLands#24]
![2019-09-28_03 48 15](https://user-images.githubusercontent.com/52297970/65810504-f0a7ef80-e1a2-11e9-929b-b42bf8bd43ec.png)
![2019-09-28_03 48 31](https://user-images.githubusercontent.com/52297970/65810505-f0a7ef80-e1a2-11e9-9adf-fe177e069848.png)
![2019-09-28_03 48 37](https://user-images.githubusercontent.com/52297970/65810506-f0a7ef80-e1a2-11e9-8040-31cdf6f19efb.png)
![2019-09-28_03 48 44](https://user-images.githubusercontent.com/52297970/65810507-f0a7ef80-e1a2-11e9-9804-bbe101870b02.png)
![2019-09-28_03 48 49](https://user-images.githubusercontent.com/52297970/65810508-f0a7ef80-e1a2-11e9-9161-305fbed6aeea.png)
![2019-09-28_03 49 29](https://user-images.githubusercontent.com/52297970/65810513-06b5b000-e1a3-11e9-9019-7db6c374f28a.png)

**Comment by cs127** [comment]
doesn't this happen in vanilla?

**Comment by muzikbike** [comment]
closing as the notice on this mod's readme has announced discontinuation for a while now - feel free to reopen in future if work starts again
