### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by triarawn** [polgaria/FarLands#26]
This mod will crash my minecraft multiple times. All of my tests on it, it has crashed pretty much every single time. 

The image of the crash: https://imgur.com/a/uFku7LF

**Comment by muzikbike** [comment]
I don't think it's yet compatible with 19w39a, I've been using 37a in the meantime.

**Comment by geniiii** [comment]
the crash report you've sent seems to have more to do with Mod Menu than FarLands...
