### ISSUE TITLE
Unable to get working in 1.14.4

### ISSUE THREAD

**Issue by vonshep** [polgaria/FarLands#31]
I've tried several ways to get the mod to work using "Fabric loader 0.7.1 build 173 (1.14.4)". I've used the mod by itself, with Fabric-API-1.14.4, and also with Cloth-Config-API-Fabric-1.14.4. I've been looking around several sites for a solution, but no luck. I've attached three crash reports of different attempts with and without the Fabric API and Cloth-Config-API. Some sites say the API is needed, and another one mentioned the Cloth-Config was needed in addition to the API. I'm hoping the crash reports will help narrow down the problem, because I would love to be able to get this to work.

[crash-2019-11-26_21.28.06-server.txt](https://github.com/polgaria/FarLands/files/3895524/crash-2019-11-26_21.28.06-server.txt)
[crash-2019-11-26_21.30.58-server.txt](https://github.com/polgaria/FarLands/files/3895525/crash-2019-11-26_21.30.58-server.txt)
[crash-2019-11-26_21.32.49-server.txt](https://github.com/polgaria/FarLands/files/3895526/crash-2019-11-26_21.32.49-server.txt)

**Comment by geniiii** [comment]
will look into it later today (most likely)

On November 27, 2019 9:07:26 AM GMT+02:00, vonshep <notifications@github.com> wrote:
>I've tried several ways to get the mod to work using "Fabric loader
>0.7.1 build 173 (1.14.4)". I've used the mod by itself, with
>Fabric-API-1.14.4, and also with Cloth-Config-API-Fabric-1.14.4. I've
>been looking around several sites for a solution, but no luck. I've
>attached three crash reports of different attempts with and without the
>Fabric API and Cloth-Config-API. Some sites say the API is needed, and
>another one mentioned the Cloth-Config was needed in addition to the
>API. I'm hoping the crash reports will help narrow down the problem,
>because I would love to be able to get this to work.
>
>[crash-2019-11-26_21.28.06-server.txt](https://github.com/polgaria/FarLands/files/3895524/crash-2019-11-26_21.28.06-server.txt)
>[crash-2019-11-26_21.30.58-server.txt](https://github.com/polgaria/FarLands/files/3895525/crash-2019-11-26_21.30.58-server.txt)
>[crash-2019-11-26_21.32.49-server.txt](https://github.com/polgaria/FarLands/files/3895526/crash-2019-11-26_21.32.49-server.txt)
>
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/polgaria/FarLands/issues/31

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by 3L3V3N3** [comment]
looks same for me, I hope it'll be fixed soon

**Comment by vonshep** [comment]
Not sure if this helps, but I read about the mod at the link below. This is why I tried with and without the API and Cloth-Config, because the actual Mod page doesn't mention anything about needing the API... just Fabric Loader.
[http://www.9minecraft.net/farlands-mod/](url)

**Comment by geniiii** [comment]
please download from the CurseForge page and try again
