### ISSUE TITLE
Can you edit the .jar file, so you can make the estimated lands closer?

### ISSUE THREAD

**Issue by average911** [polgaria/FarLands#32]

**Comment by geniiii** [comment]
..what?

**Comment by geniiii** [comment]
closing as i have absolutely no idea what you mean i'm sorry

**Comment by youdontknowmyname** [comment]
he said: "can you edit the .jar file to move the far lands closer?"

**Comment by youdontknowmyname** [comment]
apparently, no you can't.

**Comment by youdontknowmyname** [comment]
but you can move the farlands closer by increasing the coordinate scale, like in [this](https://www.youtube.com/watch?v=H5XBotoWAp8) video.
