### ISSUE TITLE
Remove floating point precision error fixes that have now been implemented into the game

### ISSUE THREAD

**Issue by muzikbike** [polgaria/FarLands#33]
1.15 prerelease 4 fixes a lot of these errors on their own, so they can be safely removed from the mod now.

A list of errors which are confirmed fixed can be found [here.](https://minecraft.gamepedia.com/Java_Edition_1.15_Pre-release_4) Ones currently still affecting the latest version are listed [here.](https://bugs.mojang.com/issues/?jql=labels+%3D+precision-loss)

**Comment by muzikbike** [comment]
I assume this has been done?

**Comment by geniiii** [comment]
> I assume this has been done?

yup
