### ISSUE TITLE
crash on world load (1.14.4)

### ISSUE THREAD

**Issue by ashencloud** [polgaria/FarLands#41]
[crash-2019-12-25_17.09.49-server.txt](https://github.com/polgaria/FarLands/files/4001018/crash-2019-12-25_17.09.49-server.txt)
When I load a world the game crashes, I looked already at other people having this issue but it doesnt seem to match what im having. I tried with and without fabric API loaded. Im using Fabric Loader 0.7.2+build.175 through multimc

**Comment by geniiii** [comment]
might not be fixed, mod will likely be updated to 1.15/1.16

**Comment by youdontknowmyname** [comment]
mah boi, yo using teh wrong version of mod
