### ISSUE TITLE
Config options do not seem to save at all

### ISSUE THREAD

**Issue by muzikbike** [polgaria/FarLands#50]
When config options are changed through /farlands, closing the game and reentering it will show them all reset to the default values.

**Comment by geniiii** [comment]
ah, my favorite type of issues; the ones that I think I've fixed.. and then they show up again.

**Comment by muzikbike** [comment]
the json5 file also appears to be somewhat blank in terms of config options

**Comment by geniiii** [comment]
> the json5 file also appears to be somewhat blank in terms of config options

indeed, this isn't the first time this issue has shown up

**Comment by geniiii** [comment]
Fixed, I hope. (both 1.15.2 and 20w06a)
Will keep the issue open until the CurseForge releases are approved.

**Comment by geniiii** [comment]
Closing, please reopen if it still somehow happens.

**Comment by muzikbike** [comment]
...wait, there's a 20w06a version available?
