### ISSUE TITLE
Change lighting fix warning to detail server crash risk

### ISSUE THREAD

**Issue by muzikbike** [polgaria/FarLands#51]
To reproduce:

1. Create a new world
2. /farlands then turn off far lands generation
3. Teleport to exactly 67 million on both axes
4. /farlands, then activate lighting fix
5. Open AltF3 performance graphs so you can see client and server performance
6. Fly into unloaded chunks

The game then appears to proceed into a frozen state where the server is completely unresponsive and the game can only be quit via the task manager. This seems like a relatively new bug since I haven't been hit with it in the past. Was trying to test if #12 was actually still an issue at all, so this kind of blocks me from doing that.

**Comment by muzikbike** [comment]
A somewhat unrelated request: can the 1.6.x project be updated? There's a closed issue in to do which should probably be replaced with newer tickets about particle floats precision loss, and other stuff.

**Comment by geniiii** [comment]
The lighting fix doesn't quite work correctly without restarting the game (`site.geni.farlands.mixins.common.util.math.BlockPosMixin`), I should probably add a warning about it. Will keep this issue open until then.

**Comment by muzikbike** [comment]
There definitely used to be a warning of some sort. Of course the fix is currently useless due to the config bug, so that needs to be sorted out first.

Also I've tested passive spawning using an even weirder method and it seems to be fixed no matter what.

**Comment by geniiii** [comment]
Ah, never mind, there is a warning. Issue is, it states that it has no effect until the game is restarted, even though there is one; breaking everything.
