### ISSUE TITLE
Labels appear when mousing over non-button areas

### ISSUE THREAD

**Issue by muzikbike** [polgaria/FarLands#55]
Not exactly helpful.
![2020-02-09_18 25 36](https://user-images.githubusercontent.com/52297970/74107595-ad568800-4b69-11ea-84b7-0260d15cda2b.png)
![2020-02-09_18 25 37](https://user-images.githubusercontent.com/52297970/74107596-adef1e80-4b69-11ea-9b8d-ccf4a24bf8f4.png)
![2020-02-09_18 25 48](https://user-images.githubusercontent.com/52297970/74107597-adef1e80-4b69-11ea-898c-8e26aa6ebffa.png)
![2020-02-09_18 25 50](https://user-images.githubusercontent.com/52297970/74107598-ae87b500-4b69-11ea-84e2-a3578706ae51.png)
![2020-02-09_18 25 18](https://user-images.githubusercontent.com/52297970/74107599-ae87b500-4b69-11ea-94c0-c35f4a47de15.png)
![2020-02-09_18 25 19](https://user-images.githubusercontent.com/52297970/74107600-af204b80-4b69-11ea-9fa0-65dead557ff0.png)
![2020-02-09_18 25 21](https://user-images.githubusercontent.com/52297970/74107601-af204b80-4b69-11ea-97d7-833f1fa80700.png)
![2020-02-09_18 25 22](https://user-images.githubusercontent.com/52297970/74107603-afb8e200-4b69-11ea-8a0b-fd149b16bb77.png)

**Comment by geniiii** [comment]
This is an issue with [ClothConfig](https://github.com/shedaniel/ClothConfig), not FarLands. You could make a feature request there.
