### ISSUE TITLE
Update to 20w09a

### ISSUE THREAD

**Issue by geniiii** [polgaria/FarLands#61]

**Comment by muzikbike** [comment]
haven't done much testing myself, but there doesn't seem to be any major problems with farlands 20w07a unless i've missed something

**Comment by geniiii** [comment]
Just updating the bundled libraries wouldn't be a bad idea anyways.

**Comment by muzikbike** [comment]
change to 08a

**Comment by geniiii** [comment]
Done in 396958db3e623c38e226eb92540e2d0eb163d471

**Comment by geniiii** [comment]
Builds will be released tomorrow, it's 4am here and I haven't really done any testing at all.
