### ISSUE TITLE
Update to 1.17

### ISSUE THREAD

**Issue by muzikbike** [polgaria/FarLands#67]
Haven't tested it on 20w12a but it probably doesn't work.

**Comment by muzikbike** [comment]
Still haven't tested it but am considerably more sure it doesn't work on 20w17a

**Comment by muzikbike** [comment]
it's been a while, I'm pretty desperate to explore far distances with the new features to see what else needs done

**Comment by geniiii** [comment]
Really gotta get to this soon, been a bit burnt out on coding lately. (man do I wonder why..
![image](https://user-images.githubusercontent.com/24881499/81460528-a95cf500-91ae-11ea-8073-d84f76628e9a.png) 
![image](https://user-images.githubusercontent.com/24881499/81460531-ac57e580-91ae-11ea-8aea-76775cb23147.png)
)

**Comment by muzikbike** [comment]
you reckon that, when you have it updated to the latest snapshot, you could commit the high distance fixes to carpet mod instead, so you don't need to deal with them and can instead just focus on the far lands? since carpet mod is focused on fixes they'd fit right in

**Comment by geniiii** [comment]
> you reckon that, when you have it updated to the latest snapshot, you could commit the high distance fixes to carpet mod instead, so you don't need to deal with them and can instead just focus on the far lands? since carpet mod is focused on fixes they'd fit right in

Sounds good to me.

**Comment by muzikbike** [comment]
and the extension of the world border as a separate sort of module, although you'll probably have to limit it to just before 2^31 instead.

having this all be the one independent mod seems like the appealing option again...

**Comment by geniiii** [comment]
I doubt we'll be seeing any more major changes, expect an update <sup>(somewhat)</sup>soon

**Comment by SolidBlock-cn** [comment]
Hoping the update as well.

**Comment by SolDev69** [comment]
rename to 1.16.4

**Comment by Jarfeh** [comment]
This is a reddit page, but I wonder if this could help in updating to later versions?
https://www.reddit.com/r/Minecraft/comments/2su65c/i_resurrected_the_far_lands_in_181/
It has files for versions 1.6.4 through 1.16.4

**Comment by toxic-guyispro** [comment]
when will this get updated to 1.17.1?!

**Comment by muzikbike** [comment]
> when will this get updated to 1.17.1?!

Never:

> Past and recent developments regarding the Fabric mod loader and its community and management have led me to believe the project is doomed. Having already lost interest in Minecraft modding and Minecraft itself long ago, I have no interest in keeping up with project splits or forks. As such, I have no plans to continue development of any of my mods for the foreseeable future.
