### ISSUE TITLE
Causes severe issues when run on a fabricloader server [19w13b]

### ISSUE THREAD

**Issue by steampunko** [polgaria/FarLands#7]
When I run a fabricloader server with this mod installed, breaking or right clicking on any block results in it disappearing on the clients end. The block is still there, and you can't move into the location where the block would be.
![2019-03-30_13 58 29](https://user-images.githubusercontent.com/16859299/55281595-fc018780-52f3-11e9-86b1-0fd86915eacc.png)

I know this mod is the issue because I don't have any other fabric mods installed, other than fabric api.

Edit: even without fabric api the same result happens when I break or right click blocks

**Comment by steampunko** [comment]
So I think I might know what's going on, I was messing around with the issue and I realized that the client might see the blocks initially, but think the world generation is completely different, therefor when I interact with blocks they get "replaced" with what the client thinks it should be,

![2019-03-30_14 20 31](https://user-images.githubusercontent.com/16859299/55281819-096c4100-52f7-11e9-9a6a-5ab9d749f925.png)
![2019-03-30_14 20 26](https://user-images.githubusercontent.com/16859299/55281820-0b360480-52f7-11e9-8a7d-9bdeb04cbb51.png)
![2019-03-30_14 20 19](https://user-images.githubusercontent.com/16859299/55281823-0c673180-52f7-11e9-8d29-f36933051de5.png)

**Comment by geniiii** [comment]
i actually haven't tested this mod much on a server, i'll try to reproduce this issue tomorrow

**Comment by geniiii** [comment]
this seems to be due to inconsistencies between the server and client `BlockPos` (caused by the Fix Lighting option being enabled server-side, but not client-side). unfortunately i'll just have to disable the Fix Lighting option by default, as i can't really think of any ways to somehow fix this. sorry

**Comment by steampunko** [comment]
Alright, thank you for responding
