### ISSUE TITLE
Conflicting with Carpet mixin

### ISSUE THREAD

**Issue by AstragoDE** [polgaria/FarLands#70]
Here is the Report: https://gist.githubusercontent.com/Cloak-Bot/e2446d5d5b488b1593221cae8aab075e/raw/5d3a196ced11a63618e20a0d2be26b9fd3c6174b/crash.txt

**Comment by geniiii** [comment]
Looks like it's conflicting with a Carpet mixin.

**Comment by AstragoDE** [comment]
thanks for your help
