### ISSUE TITLE
Crash Upon Clicking Options Menu

### ISSUE THREAD

**Issue by AJMFactsheets** [polgaria/FarLands#8]
Hello,
I have tried installing the mod with multiple versions of fabric, but I always get the same crash (MixinsTransformer) whenever I click singleplayer or go to the options menu. I have tried this on multiple computers and I get a similar error.

I am using the "[1.14 Pre-Release 3] v1.4" version from the curseforge download page.

See the cash report attached below
[crash-2019-04-18_16.07.23-client.txt](https://github.com/polgaria/FarLands/files/3096197/crash-2019-04-18_16.07.23-client.txt)

**Comment by geniiii** [comment]
could you retest with the latest release?

**Comment by AJMFactsheets** [comment]
I retested with the latest versions and everything seems to work. Did you remove the GUI buttons for customizing the mod? They seem to have vanished in this version. Nevertheless, the json config still works fine and I enjoyed exploring the farlands! 💯

**Comment by geniiii** [comment]
not removed, switched over to a command to prevent conflicts with other mods adding a button in the same spots  
try `/farlands`
