### ISSUE TITLE
Ability to offset terrain instead of stretching it

### ISSUE THREAD

**Issue by muzikbike** [polgaria/FarLands#80]
https://github.com/ThisTestUser/FarLandsChronicles/blob/master/Chapter%202%20-%20The%20Far%20Lands%20in%201.12.2/Part%202.5%20-%20Shifting%20the%20Far%20Lands.md 

This would allow terrain otherwise only accessible via #13 to be seen without severely distorting the normal terrain in the world. However, such a feature would likely be grossly invasive and suck for compatibility, so I'm not sure if it would warrant a separate submod or something.

**Comment by geniiii** [comment]
It could be locked behind a setting.

**Comment by greg-guy** [comment]
you sound like you glow in the dark

**Comment by ThisTestUser** [comment]
Actually, since chunk coords are stored as integers, shifting the terrain would only allow you to generate terrain up to 16*2^31.

**Comment by muzikbike** [comment]
closing as the notice on this mod's readme has announced discontinuation for a while now - feel free to reopen in future if work starts again
