### ISSUE TITLE
Remove ore gen fix

### ISSUE THREAD

**Issue by muzikbike** [polgaria/FarLands#82]
Assuming, you know, they've actually fixed it in the next development version, and not instead fixed the diagonal decoration repetition quirk I used to make it easily visible.

https://bugs.mojang.com/browse/MC-185925

**Comment by muzikbike** [comment]
Is this fixed by #79?

**Comment by geniiii** [comment]
> Is this fixed by #79?

`OreFeatureMixin` is gone, although it appears I've left in the config option on accident.

**Comment by muzikbike** [comment]
closing as the notice on this mod's readme has announced discontinuation for a while now - feel free to reopen in future if work starts again
