### ISSUE TITLE
your addon sucks

### ISSUE THREAD

**Issue by demiena** [polgaria/FarLands#84]
My game crashes when I am trying to start it up. I don't have a crashlog because it's an unexpected issue.

**Comment by david73754** [comment]
why is this invalid? how is this invalid? its not!

**Comment by geniiii** [comment]
> why is this invalid? how is this invalid? its not!

Lack of crash log, invalid title. Stupid issues like this only contribute to the burnout mod developers often experience.

**Comment by Jarfeh** [comment]
You are doing an amazing job geniiii! Don't let people's rudeness bring you down, take as much time as you need :)

**Comment by youdontknowmyname** [comment]
yea!

**Comment by youdontknowmyname** [comment]
also, this does not crash on 1.14 fabric

**Comment by youdontknowmyname** [comment]
btw, you could just close this as incomplete, not invalid!

**Comment by Jarfeh** [comment]
> 
> 
> btw, you could just close this as incomplete, not invalid!

I think it's best to leave it as invalid, since they did not include any crash logs, and were incredibly rude with the title of their "issue".
