### ISSUE TITLE
Fix sculk sensor vibrations appearing from the wrong locations

### ISSUE THREAD

**Issue by muzikbike** [polgaria/FarLands#86]
Probably pretty closely tied to #17.

![2020-12-03_10 49 30](https://user-images.githubusercontent.com/52297970/101000182-6f41af00-3555-11eb-8b72-3ed00543a04f.png)
![2020-12-03_10 49 48](https://user-images.githubusercontent.com/52297970/101000187-710b7280-3555-11eb-93f1-49cbdaf09980.png)
![2020-12-03_10 49 58](https://user-images.githubusercontent.com/52297970/101000193-723c9f80-3555-11eb-97b9-c61bfb557d29.png)

**Comment by Jarfeh** [comment]
Wait, there's a version of the farlands mod for snapshot 1.17?

**Comment by geniiii** [comment]
> Wait, there's a version of the farlands mod for snapshot 1.17?

No, but there probably will be after I update to 1.16.4. This is an issue for a future version.

**Comment by Jarfeh** [comment]
Ah

**Comment by muzikbike** [comment]
closing as the notice on this mod's readme has announced discontinuation for a while now - feel free to reopen in future if work starts again
