### ISSUE TITLE
Certain particles still use incorrect floats

### ISSUE THREAD

**Issue by muzikbike** [polgaria/FarLands#9]
Found to affect the following:

- /particle particles
- Particles from breaking armour stands
- Particles from falling
- Particles from damaging a mob
- Particles from sweep attacks

**Comment by geniiii** [comment]
i know about these; the issue is that i'd need to rewrite the particle packet to fix them, which isn't a very good thing to do when it comes to compatibility, lol

**Comment by muzikbike** [comment]
Particles from adding eyes to end portal frames also lose precision:

![2019-09-08_18 37 40](https://user-images.githubusercontent.com/52297970/64492083-de9ff480-d267-11e9-9021-61d5be8221eb.png)

**Comment by muzikbike** [comment]
I've found a few more examples of particles losing precision; let me know if any of these seem reasonably fixable so I can open an issue for them.

- Particles from activated conduits
- Particles from end gateways
- Particles from fishing (both splashes and moving fish thing)
- Squid ink particles

**Comment by geniiii** [comment]
end gateway particles should be fixed in fb5c0735fa34d5b624964f33f980966bccab0b77  
another i've found: campfire particles

**Comment by muzikbike** [comment]
Conduit and end gateway particles will be fixed in the next vanilla prerelease

**Comment by muzikbike** [comment]
Almost all of them are fixed in pre4. All I can find that still exist are bone meal and eye of enderortal frame addition particles. They also fixed tnt and enchanting tables.

**Comment by muzikbike** [comment]
Since there's so few of them currently in the game now I'll probably close this ticket and create individual tickets here instead

**Comment by muzikbike** [comment]
Closing this ticket until a playable version for 1.15 or 1.16 comes out, so then I can report any cases I find individually. Having a bunch of random particle bugs in one issue just causes clutter.
